### PR TITLE
Test RelocateSegment used before computing used

### LINKED ISSUE #121: Test segment relocation without computing segment sizes before
Test `MemorySegmentManager.RelocateSegments` method without computing segment sizes before. The test should expect the method to return `nil, false`.

To achieve this, [the first condition in the method](https://github.com/lambdaclass/cairo-vm.go/blob/736c56caff01310f17ee35cb8d8ac5e1e8e28766/pkg/vm/memory/segments.go#L44) must be fixed. It should be `len(m.SegmentSizes) == 0` instead of `m.SegmentSizes == nil`.

The method is defined [here](https://github.com/lambdaclass/cairo-vm.go/blob/736c56caff01310f17ee35cb8d8ac5e1e8e28766/pkg/vm/memory/segments.go#L43-L58).

### PR DESCRIPTION
**Pull request by mattcoburn24**
closes #121 
added TestRelocateSegmentUsedSizeBeforeComputingSegment

### CODE REVIEW

**Comment by toni-calvin** [comment]
The issue is being reformulated, when conversation is resolved this PR should be updated to the new changes.

**Comment by gabrielbosio** [comment]
I've updated the issue: https://github.com/lambdaclass/cairo-vm.go/issues/121#issue-1846924219

**Comment by gabrielbosio** [comment]
Now that the issue is updated, this PR must change [the first condition in the method](https://github.com/lambdaclass/cairo-vm.go/blob/736c56caff01310f17ee35cb8d8ac5e1e8e28766/pkg/vm/memory/segments.go#L44). It should be `len(m.SegmentSizes) == 0` instead of `m.SegmentSizes == nil`.
This should break the added test, because it expects `ok` to be `true` when in reality it should expect `false`.

**Comment by jrchatruc** [comment]
Also closing it out for inactivity, @greged93 you can open a new one if the changes are made

**Pull request closed without merging**
